<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>WorkStudio</RootNamespace>
    <AssemblyName>WorkStudio</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\Mod\Assemblies\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*-*" />
    <PackageReference Include="Krafs.Publicizer" Version="2.*" PrivateAssets="all" />
    <PackageReference Include="Lib.Harmony" Version="2.*">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Publicize Include="Assembly-CSharp" />
  </ItemGroup>

</Project>
